export const products = [
  {
    id: "urban-runner",
    slug: "urban-runner",
    name: "Urban Runner",
    category: "Sneakers",
    price: 180,
    image: "/sneakers 3.jpg",
    rating: "4.8",
    tag: "New",
    description: "A lightweight everyday runner with a soft, responsive step and a clean silhouette.",
    details: ["Breathable mesh upper", "Cushioned foam midsole", "Rubber grip outsole"],
    colors: ["#f1f0ed", "#1d1d1d", "#8c9f75"],
  },
  {
    id: "sable-loafer",
    slug: "sable-loafer",
    name: "Sable Loafer",
    category: "Loafers",
    price: 150,
    image: "/Blackloafers.png",
    rating: "4.9",
    tag: "Bestseller",
    description: "A polished, easy-wearing loafer made for workdays, weekends, and every plan in between.",
    details: ["Smooth vegan leather upper", "Soft lined footbed", "Low-profile rubber sole"],
    colors: ["#181818", "#694a3a", "#eee9df"],
  },
  {
    id: "terrace-slide",
    slug: "terrace-slide",
    name: "Terrace Slide",
    category: "Sandals",
    price: 95,
    image: "/sandals.png",
    rating: "4.6",
    tag: "Easy days",
    description: "A relaxed slide with a supportive contour for sunlit errands and unhurried afternoons.",
    details: ["Padded adjustable strap", "Contoured footbed", "Water-friendly finish"],
    colors: ["#dfd3c3", "#2e2c29", "#a5b7a4"],
  },
  {
    id: "cloud-nine",
    slug: "cloud-nine",
    name: "Cloud Nine",
    category: "Sneakers",
    price: 165,
    image: "/sneakers 2.jpg",
    rating: "4.7",
    tag: "New",
    description: "A cushioned trainer designed for long days on your feet, without sacrificing a sharp look.",
    details: ["Pillow-soft heel collar", "Flexible lightweight sole", "Lace-up secure fit"],
    colors: ["#ebeee9", "#39465b", "#d99d7b"],
  },
  {
    id: "everyday-loafer",
    slug: "everyday-loafer",
    name: "Everyday Loafer",
    category: "Loafers",
    price: 145,
    image: "/shoe 1.jpg",
    rating: "4.9",
    tag: "Editor’s pick",
    description: "A quietly refined loafer with a soft feel from the first wear and room for a full day ahead.",
    details: ["Supple textured upper", "Cushioned insole", "Flexible stitched outsole"],
    colors: ["#835b42", "#181818", "#efe6d9"],
  },
  {
    id: "sunset-strap",
    slug: "sunset-strap",
    name: "Sunset Strap",
    category: "Sandals",
    price: 110,
    image: "/sandals.jpg",
    rating: "4.5",
    tag: "Summer",
    description: "An adjustable sandal that keeps summer plans comfortable, easy, and put together.",
    details: ["Dual adjustable straps", "Molded comfort footbed", "Light traction sole"],
    colors: ["#c69367", "#ebdfc7", "#5a5d50"],
  },
  { id: "atlas-court", slug: "atlas-court", name: "Atlas Court", category: "Sneakers", price: 175, image: "/sneakers 1.jpg", rating: "4.8", tag: "New", description: "A clean court sneaker with understated lines and day-long cushioning.", details: ["Leather-look upper", "Padded collar", "Flexible cupsole"], colors: ["#f6f2e9", "#27303a", "#b05242"] },
  { id: "dune-walk", slug: "dune-walk", name: "Dune Walk", category: "Sandals", price: 105, image: "/sandals.jpg", rating: "4.7", tag: "Warm weather", description: "A versatile walking sandal with an easy secure fit for bright, busy days.", details: ["Secure ankle strap", "Cushioned base", "Textured outsole"], colors: ["#be8b68", "#f0e2c8", "#7b866d"] },
  { id: "cambridge-penny", slug: "cambridge-penny", name: "Cambridge Penny", category: "Loafers", price: 160, image: "/Blackloafers.png", rating: "4.8", tag: "Classic", description: "A modern penny loafer that makes tailoring and denim feel equally effortless.", details: ["Polished upper", "Comfort lining", "Grip rubber heel"], colors: ["#171717", "#623f31", "#e9dfd0"] },
  { id: "ozone-runner", slug: "ozone-runner", name: "Ozone Runner", category: "Sneakers", price: 190, image: "/hero-shoe.svg", rating: "4.9", tag: "Limited", description: "A standout runner built with soft structure and a surprisingly light ride.", details: ["Engineered knit upper", "High-rebound foam", "Stabilising heel counter"], colors: ["#f0eeea", "#1c1c1c", "#9baf72"] },
  { id: "lyon-platform", slug: "lyon-platform", name: "Lyon Platform", category: "Sneakers", price: 185, image: "/sneakers 2.jpg", rating: "4.6", tag: "Fresh", description: "A lifted everyday sneaker that adds a little height without losing comfort.", details: ["Soft textile upper", "Platform foam base", "Extra grip tread"], colors: ["#e9ebe7", "#4b596d", "#cc997f"] },
  { id: "voyager-mule", slug: "voyager-mule", name: "Voyager Mule", category: "Loafers", price: 155, image: "/shoe 1.jpg", rating: "4.7", tag: "Travel edit", description: "An easy slip-on mule designed for a polished look with no breaking-in period.", details: ["Soft textured upper", "Open-back comfort", "Cushioned sole"], colors: ["#7c543c", "#181818", "#e9dfd1"] },
];

export function getProduct(slug) {
  return products.find((product) => product.slug === slug);
}
