export const products = [
  {
    id: "urban-runner",
    slug: "urban-runner",
    name: "Urban Runner",
    category: "Sneakers",
    price: 180,
    image: "/sneakers 3.jpg",
    rating: "4.8",
    tag: "New",
    description: "A lightweight everyday runner with a soft, responsive step and a clean silhouette.",
    details: ["Breathable mesh upper", "Cushioned foam midsole", "Rubber grip outsole"],
    colors: ["#f1f0ed", "#1d1d1d", "#8c9f75"],
  },
  {
    id: "sable-loafer",
    slug: "sable-loafer",
    name: "Sable Loafer",
    category: "Loafers",
    price: 150,
    image: "/Blackloafers.png",
    rating: "4.9",
    tag: "Bestseller",
    description: "A polished, easy-wearing loafer made for workdays, weekends, and every plan in between.",
    details: ["Smooth vegan leather upper", "Soft lined footbed", "Low-profile rubber sole"],
    colors: ["#181818", "#694a3a", "#eee9df"],
  },
  {
    id: "terrace-slide",
    slug: "terrace-slide",
    name: "Terrace Slide",
    category: "Sandals",
    price: 95,
    image: "/sandals.png",
    rating: "4.6",
    tag: "Easy days",
    description: "A relaxed slide with a supportive contour for sunlit errands and unhurried afternoons.",
    details: ["Padded adjustable strap", "Contoured footbed", "Water-friendly finish"],
    colors: ["#dfd3c3", "#2e2c29", "#a5b7a4"],
  },
  {
    id: "cloud-nine",
    slug: "cloud-nine",
    name: "Cloud Nine",
    category: "Sneakers",
    price: 165,
    image: "/sneakers 2.jpg",
    rating: "4.7",
    tag: "New",
    description: "A cushioned trainer designed for long days on your feet, without sacrificing a sharp look.",
    details: ["Pillow-soft heel collar", "Flexible lightweight sole", "Lace-up secure fit"],
    colors: ["#ebeee9", "#39465b", "#d99d7b"],
  },
  {
    id: "everyday-loafer",
    slug: "everyday-loafer",
    name: "Everyday Loafer",
    category: "Loafers",
    price: 145,
    image: "/shoe 1.jpg",
    rating: "4.9",
    tag: "Editor’s pick",
    description: "A quietly refined loafer with a soft feel from the first wear and room for a full day ahead.",
    details: ["Supple textured upper", "Cushioned insole", "Flexible stitched outsole"],
    colors: ["#835b42", "#181818", "#efe6d9"],
  },
  {
    id: "sunset-strap",
    slug: "sunset-strap",
    name: "Sunset Strap",
    category: "Sandals",
    price: 110,
    image: "/sandals.jpg",
    rating: "4.5",
    tag: "Summer",
    description: "An adjustable sandal that keeps summer plans comfortable, easy, and put together.",
    details: ["Dual adjustable straps", "Molded comfort footbed", "Light traction sole"],
    colors: ["#c69367", "#ebdfc7", "#5a5d50"],
  },
  { id: "atlas-court", slug: "atlas-court", name: "Atlas Court", category: "Sneakers", price: 175, image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=85", rating: "4.8", tag: "New", description: "A clean court sneaker with understated lines and day-long cushioning.", details: ["Leather-look upper", "Padded collar", "Flexible cupsole"], colors: ["#f6f2e9", "#27303a", "#b05242"] },
  { id: "dune-walk", slug: "dune-walk", name: "Dune Walk", category: "Sandals", price: 105, image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1000&q=85", rating: "4.7", tag: "Warm weather", description: "A versatile walking sandal with an easy secure fit for bright, busy days.", details: ["Secure ankle strap", "Cushioned base", "Textured outsole"], colors: ["#be8b68", "#f0e2c8", "#7b866d"] },
  { id: "cambridge-penny", slug: "cambridge-penny", name: "Cambridge Penny", category: "Loafers", price: 160, image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=85", rating: "4.8", tag: "Classic", description: "A modern penny loafer that makes tailoring and denim feel equally effortless.", details: ["Polished upper", "Comfort lining", "Grip rubber heel"], colors: ["#171717", "#623f31", "#e9dfd0"] },
  { id: "ozone-runner", slug: "ozone-runner", name: "Ozone Runner", category: "Sneakers", price: 190, image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=85", rating: "4.9", tag: "Limited", description: "A standout runner built with soft structure and a surprisingly light ride.", details: ["Engineered knit upper", "High-rebound foam", "Stabilising heel counter"], colors: ["#f0eeea", "#1c1c1c", "#9baf72"] },
  { id: "lyon-platform", slug: "lyon-platform", name: "Lyon Platform", category: "Sneakers", price: 185, image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=1000&q=85", rating: "4.6", tag: "Fresh", description: "A lifted everyday sneaker that adds a little height without losing comfort.", details: ["Soft textile upper", "Platform foam base", "Extra grip tread"], colors: ["#e9ebe7", "#4b596d", "#cc997f"] },
  { id: "voyager-mule", slug: "voyager-mule", name: "Voyager Mule", category: "Loafers", price: 155, image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=1000&q=85", rating: "4.7", tag: "Travel edit", description: "An easy slip-on mule designed for a polished look with no breaking-in period.", details: ["Soft textured upper", "Open-back comfort", "Cushioned sole"], colors: ["#7c543c", "#181818", "#e9dfd1"] },
  { id: "midnight-stride", slug: "midnight-stride", name: "Midnight Stride", category: "Sneakers", price: 170, image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1000&q=85", rating: "4.8", tag: "Night edit", description: "A streamlined street runner with a low-key profile and a high-comfort interior.", details: ["Structured knit upper", "Impact-absorbing sole", "Reflective heel detail"], colors: ["#222222", "#e7e2d8", "#405363"] },
  { id: "motion-form", slug: "motion-form", name: "Motion Form", category: "Sneakers", price: 195, image: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=1000&q=85", rating: "4.9", tag: "Performance", description: "A technical trainer that pairs bold energy with all-day stability.", details: ["Breathable engineered mesh", "Responsive support foam", "High-traction outsole"], colors: ["#f6f6f4", "#222c42", "#db8f72"] },
  { id: "harbour-penny", slug: "harbour-penny", name: "Harbour Penny", category: "Loafers", price: 165, image: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&w=1000&q=85", rating: "4.7", tag: "Refined", description: "A quietly confident penny loafer for tailoring, denim, and everything in between.", details: ["Polished upper", "Cushioned heel pad", "Flexible grip sole"], colors: ["#211c19", "#7b4c33", "#ddd4c6"] },
  { id: "weekend-low", slug: "weekend-low", name: "Weekend Low", category: "Sneakers", price: 145, image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=1000&q=85", rating: "4.6", tag: "Everyday", description: "A relaxed low-top made for slow starts, quick errands, and easy plans.", details: ["Soft canvas upper", "Padded footbed", "Flexible rubber base"], colors: ["#f2efe6", "#313c42", "#b36a4e"] },
  { id: "city-sprint", slug: "city-sprint", name: "City Sprint", category: "Sneakers", price: 180, image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=1000&q=85", rating: "4.8", tag: "Street ready", description: "A confident runner for fast city days and laid-back nights out.", details: ["Lightweight textile upper", "Spring foam midsole", "Durable traction sole"], colors: ["#f1f0ea", "#253c49", "#bc6d56"] },
  { id: "canvas-shift", slug: "canvas-shift", name: "Canvas Shift", category: "Sneakers", price: 135, image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=1000&q=85", rating: "4.6", tag: "Weekend", description: "A clean canvas trainer that adds an easy finish to any off-duty look.", details: ["Durable canvas upper", "Padded ankle collar", "Classic rubber sole"], colors: ["#f5f1e9", "#232323", "#98aa8b"] },
];

export function getProduct(slug) {
  return products.find((product) => product.slug === slug);
}
